# Generated by Django 4.0.4 on 2022-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Mystery', 'Mystery'), ('Historical fiction', 'Historical fiction'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Adventure', 'Adventure'), ('Dystopian', 'Dystopian'), ('Paranormal', 'Paranormal'), ('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Children’s', 'Children’s'), ('Contemporary', 'Contemporary')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
