# Generated by Django 4.0.4 on 2022-05-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Historical fiction', 'Historical fiction'), ('Romance', 'Romance'), ('Contemporary', 'Contemporary'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Adventure', 'Adventure'), ('Paranormal', 'Paranormal'), ('Dystopian', 'Dystopian'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Children’s', 'Children’s')], max_length=50),
        ),
    ]
