# Generated by Django 4.0.4 on 2022-05-07 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_main', '0002_bookmodel_available_alter_bookmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.CharField(choices=[('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Paranormal', 'Paranormal'), ('Horror', 'Horror'), ('Science Fiction', 'Science Fiction'), ('Historical fiction', 'Historical fiction'), ('Children’s', 'Children’s'), ('Adventure', 'Adventure'), ('Dystopian', 'Dystopian'), ('Contemporary', 'Contemporary')], max_length=50),
        ),
        migrations.CreateModel(
            name='BorrowBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_status', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_book', to='App_main.bookmodel')),
                ('borrowed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_by_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
